### ISSUE TITLE
Röle RX ve TX frekanslarında karışıklık

### ISSUE THREAD

**Issue by ta2bgh** [firatsoygul/TurkiyeBandPlani#1]
Merhaba,
Tablonuzda RX ve TX yerleri bu şekilde tam tersi olması gerekmiyor mu? Teşekkürler.
73

![preview](https://user-images.githubusercontent.com/84229202/119226115-45367600-bb10-11eb-8a2c-462be04ed456.png)

**Comment by firatsoygul** [comment]
Merhaba.

Oradaki ifade, kullandığımız cihazları değil de röleyi baz aldığı için bu şekilde tanımlanıyor. Yani Röle RX derken, "cihazımızın çıkış (TX) frekansı" yerine, "rölenin giriş/alış (RX) frekansını" işaret ediyoruz, ikisi de aynı frekans olmasına rağmen. 73

**Comment by ta2bgh** [comment]
Evet şimdi anladım, haklısınız.
İlginiz için teşekkürler.
73
